const express = require('express')
const router = express.Router()
const userController = require('../../../controllers/users')
const { validateUploadAvatar } = require('./validation')
const guard = require('../../../helpers/guard')
const upload = require('../../../helpers/upload')
const { createRegLimiter } = require('../../../helpers/rate-limit-reg')
router.post('/registration', createRegLimiter, userController.reg)
router.post('/login', userController.login)
router.post('/logout', guard, userController.logout)
router.get('/current', guard, userController.getCurrent)
router.patch('/avatars', [guard, upload.single('avatar'), validateUploadAvatar], userController.avatars,)
module.exports = router
